# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PhotometryConfigWidget.ui'
#
# Created: Wed May 12 15:26:03 2010
#      by: PyQt4 UI code generator 4.6.1
#
# WARNING! All changes made in this file will be lost!
#
# smc:  This file was copied over from the original repository
#       It can be modified, but if open with a qt editor
#       it will be overwritten


from PyQt5 import QtCore, QtGui

class Ui_PhotometryConfigWidget(object):
    def setupUi(self, PhotometryConfigWidget):
        PhotometryConfigWidget.setObjectName("PhotometryConfigWidget")
        PhotometryConfigWidget.resize(589, 565)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(PhotometryConfigWidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ImageSelectionWidget = QtWidgets.QWidget(PhotometryConfigWidget)
        self.ImageSelectionWidget.setObjectName("ImageSelectionWidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.ImageSelectionWidget)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.imageSpinBox = QtWidgets.QSpinBox(self.ImageSelectionWidget)
        self.imageSpinBox.setMinimum(1)
        self.imageSpinBox.setMaximum(999999999)
        self.imageSpinBox.setObjectName("imageSpinBox")
        self.horizontalLayout_10.addWidget(self.imageSpinBox)
        spacerItem = QtWidgets.QSpacerItem(257, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.previousButton = QtWidgets.QPushButton(self.ImageSelectionWidget)
        self.previousButton.setObjectName("previousButton")
        self.horizontalLayout_10.addWidget(self.previousButton)
        self.nextButton = QtWidgets.QPushButton(self.ImageSelectionWidget)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_10.addWidget(self.nextButton)
        self.verticalLayout_5.addWidget(self.ImageSelectionWidget)
        self.tabWidget = QtWidgets.QTabWidget(PhotometryConfigWidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tgtTab = QtWidgets.QWidget()
        self.tgtTab.setObjectName("tgtTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tgtTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tgtRecenterCheckBox = QtWidgets.QCheckBox(self.tgtTab)
        self.tgtRecenterCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tgtRecenterCheckBox.setChecked(True)
        self.tgtRecenterCheckBox.setObjectName("tgtRecenterCheckBox")
        self.horizontalLayout_3.addWidget(self.tgtRecenterCheckBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.lockObjectSizes = QtWidgets.QToolButton(self.tgtTab)
        icon = QtWidgets.QIcon()
        icon.addPixmap(QtWidgets.QPixmap(":/icons/icons/chain-unlocked.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        icon.addPixmap(QtWidgets.QPixmap(":/icons/icons/chain-locked.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.On)
        self.lockObjectSizes.setIcon(icon)
        self.lockObjectSizes.setCheckable(True)
        self.lockObjectSizes.setObjectName("lockObjectSizes")
        self.horizontalLayout_3.addWidget(self.lockObjectSizes)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(self.tgtTab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_12 = QtWidgets.QLabel(self.tgtTab)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tgtTab)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 1, 1, 1)
        self.tgtXLineEdit = QtWidgets.QLineEdit(self.tgtTab)
        self.tgtXLineEdit.setObjectName("tgtXLineEdit")
        self.gridLayout_5.addWidget(self.tgtXLineEdit, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tgtTab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 3, 1, 1)
        self.tgtYLineEdit = QtWidgets.QLineEdit(self.tgtTab)
        self.tgtYLineEdit.setObjectName("tgtYLineEdit")
        self.gridLayout_5.addWidget(self.tgtYLineEdit, 0, 4, 1, 1)
        self.captureTgt = QtWidgets.QPushButton(self.tgtTab)
        self.captureTgt.setCheckable(False)
        self.captureTgt.setObjectName("captureTgt")
        self.gridLayout_5.addWidget(self.captureTgt, 0, 5, 1, 1)
        self.tgtEndPosLabel = QtWidgets.QLabel(self.tgtTab)
        self.tgtEndPosLabel.setObjectName("tgtEndPosLabel")
        self.gridLayout_5.addWidget(self.tgtEndPosLabel, 1, 0, 1, 1)
        self.tgtEndXLabel = QtWidgets.QLabel(self.tgtTab)
        self.tgtEndXLabel.setObjectName("tgtEndXLabel")
        self.gridLayout_5.addWidget(self.tgtEndXLabel, 1, 1, 1, 1)
        self.tgtXEndLineEdit = QtWidgets.QLineEdit(self.tgtTab)
        self.tgtXEndLineEdit.setObjectName("tgtXEndLineEdit")
        self.gridLayout_5.addWidget(self.tgtXEndLineEdit, 1, 2, 1, 1)
        self.tgtEndYLabel = QtWidgets.QLabel(self.tgtTab)
        self.tgtEndYLabel.setObjectName("tgtEndYLabel")
        self.gridLayout_5.addWidget(self.tgtEndYLabel, 1, 3, 1, 1)
        self.tgtYEndLineEdit = QtWidgets.QLineEdit(self.tgtTab)
        self.tgtYEndLineEdit.setObjectName("tgtYEndLineEdit")
        self.gridLayout_5.addWidget(self.tgtYEndLineEdit, 1, 4, 1, 1)
        self.captureTgtEnd = QtWidgets.QPushButton(self.tgtTab)
        self.captureTgtEnd.setObjectName("captureTgtEnd")
        self.gridLayout_5.addWidget(self.captureTgtEnd, 1, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tgtTab)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tgtTab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 2, 1, 1, 1)
        self.tgtRLineEdit = QtWidgets.QLineEdit(self.tgtTab)
        self.tgtRLineEdit.setObjectName("tgtRLineEdit")
        self.gridLayout_5.addWidget(self.tgtRLineEdit, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 2, 4, 1, 1)
        self.captureTgtRadius = QtWidgets.QPushButton(self.tgtTab)
        self.captureTgtRadius.setObjectName("captureTgtRadius")
        self.gridLayout_5.addWidget(self.captureTgtRadius, 2, 5, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.tabWidget.addTab(self.tgtTab, "")
        self.tgtBackgroundTab = QtWidgets.QWidget()
        self.tgtBackgroundTab.setObjectName("tgtBackgroundTab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tgtBackgroundTab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.tgtBackgroundTab)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.tgtAnulusRadioButton = QtWidgets.QRadioButton(self.tgtBackgroundTab)
        self.tgtAnulusRadioButton.setChecked(True)
        self.tgtAnulusRadioButton.setObjectName("tgtAnulusRadioButton")
        self.horizontalLayout.addWidget(self.tgtAnulusRadioButton)
        self.tgtRegionRadioButton = QtWidgets.QRadioButton(self.tgtBackgroundTab)
        self.tgtRegionRadioButton.setObjectName("tgtRegionRadioButton")
        self.horizontalLayout.addWidget(self.tgtRegionRadioButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.allignTgtVerticalCenter = QtWidgets.QToolButton(self.tgtBackgroundTab)
        icon1 = QtWidgets.QIcon()
        icon1.addPixmap(QtWidgets.QPixmap(":/icons/icons/align-vertical-center.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.allignTgtVerticalCenter.setIcon(icon1)
        self.allignTgtVerticalCenter.setCheckable(True)
        self.allignTgtVerticalCenter.setObjectName("allignTgtVerticalCenter")
        self.horizontalLayout.addWidget(self.allignTgtVerticalCenter)
        self.lockBackgroundSize = QtWidgets.QToolButton(self.tgtBackgroundTab)
        self.lockBackgroundSize.setIcon(icon)
        self.lockBackgroundSize.setCheckable(True)
        self.lockBackgroundSize.setObjectName("lockBackgroundSize")
        self.horizontalLayout.addWidget(self.lockBackgroundSize)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tgtBackgroundTab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.captureTgtAnulusBackground = QtWidgets.QPushButton(self.groupBox_2)
        self.captureTgtAnulusBackground.setObjectName("captureTgtAnulusBackground")
        self.horizontalLayout_6.addWidget(self.captureTgtAnulusBackground)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.tgtR1LineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.tgtR1LineEdit.setObjectName("tgtR1LineEdit")
        self.gridLayout_2.addWidget(self.tgtR1LineEdit, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.tgtR2LineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.tgtR2LineEdit.setObjectName("tgtR2LineEdit")
        self.gridLayout_2.addWidget(self.tgtR2LineEdit, 1, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.tgtBackgroundTab)
        self.groupBox.setEnabled(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.captureTgtRegionBackground = QtWidgets.QPushButton(self.groupBox)
        self.captureTgtRegionBackground.setObjectName("captureTgtRegionBackground")
        self.horizontalLayout_5.addWidget(self.captureTgtRegionBackground)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.tgtX1LineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.tgtX1LineEdit.setObjectName("tgtX1LineEdit")
        self.gridLayout.addWidget(self.tgtX1LineEdit, 0, 1, 1, 1)
        self.tgtX2LineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.tgtX2LineEdit.setObjectName("tgtX2LineEdit")
        self.gridLayout.addWidget(self.tgtX2LineEdit, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.tgtY1LineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.tgtY1LineEdit.setObjectName("tgtY1LineEdit")
        self.gridLayout.addWidget(self.tgtY1LineEdit, 1, 1, 1, 1)
        self.tgtY2LineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.tgtY2LineEdit.setObjectName("tgtY2LineEdit")
        self.gridLayout.addWidget(self.tgtY2LineEdit, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tgtBackgroundTab, "")
        self.cmpTab = QtWidgets.QWidget()
        self.cmpTab.setObjectName("cmpTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.cmpTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cmpRecenterCheckBox = QtWidgets.QCheckBox(self.cmpTab)
        self.cmpRecenterCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cmpRecenterCheckBox.setChecked(True)
        self.cmpRecenterCheckBox.setObjectName("cmpRecenterCheckBox")
        self.horizontalLayout_4.addWidget(self.cmpRecenterCheckBox)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.lockObjectSizes2 = QtWidgets.QToolButton(self.cmpTab)
        self.lockObjectSizes2.setIcon(icon)
        self.lockObjectSizes2.setCheckable(True)
        self.lockObjectSizes2.setObjectName("lockObjectSizes2")
        self.horizontalLayout_4.addWidget(self.lockObjectSizes2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.line_2 = QtWidgets.QFrame(self.cmpTab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_18 = QtWidgets.QLabel(self.cmpTab)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.cmpTab)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 0, 1, 1, 1)
        self.cmpXLineEdit = QtWidgets.QLineEdit(self.cmpTab)
        self.cmpXLineEdit.setObjectName("cmpXLineEdit")
        self.gridLayout_6.addWidget(self.cmpXLineEdit, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.cmpTab)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 0, 3, 1, 1)
        self.cmpYLineEdit = QtWidgets.QLineEdit(self.cmpTab)
        self.cmpYLineEdit.setObjectName("cmpYLineEdit")
        self.gridLayout_6.addWidget(self.cmpYLineEdit, 0, 4, 1, 1)
        self.captureCmp = QtWidgets.QPushButton(self.cmpTab)
        self.captureCmp.setObjectName("captureCmp")
        self.gridLayout_6.addWidget(self.captureCmp, 0, 5, 1, 1)
        self.cmpEndPosLabel = QtWidgets.QLabel(self.cmpTab)
        self.cmpEndPosLabel.setObjectName("cmpEndPosLabel")
        self.gridLayout_6.addWidget(self.cmpEndPosLabel, 1, 0, 1, 1)
        self.cmpEndXLabel = QtWidgets.QLabel(self.cmpTab)
        self.cmpEndXLabel.setObjectName("cmpEndXLabel")
        self.gridLayout_6.addWidget(self.cmpEndXLabel, 1, 1, 1, 1)
        self.cmpXEndLineEdit = QtWidgets.QLineEdit(self.cmpTab)
        self.cmpXEndLineEdit.setObjectName("cmpXEndLineEdit")
        self.gridLayout_6.addWidget(self.cmpXEndLineEdit, 1, 2, 1, 1)
        self.cmpEndYLabel = QtWidgets.QLabel(self.cmpTab)
        self.cmpEndYLabel.setObjectName("cmpEndYLabel")
        self.gridLayout_6.addWidget(self.cmpEndYLabel, 1, 3, 1, 1)
        self.cmpYEndLineEdit = QtWidgets.QLineEdit(self.cmpTab)
        self.cmpYEndLineEdit.setObjectName("cmpYEndLineEdit")
        self.gridLayout_6.addWidget(self.cmpYEndLineEdit, 1, 4, 1, 1)
        self.captureCmpEnd = QtWidgets.QPushButton(self.cmpTab)
        self.captureCmpEnd.setObjectName("captureCmpEnd")
        self.gridLayout_6.addWidget(self.captureCmpEnd, 1, 5, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.cmpTab)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.cmpTab)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 2, 1, 1, 1)
        self.cmpRLineEdit = QtWidgets.QLineEdit(self.cmpTab)
        self.cmpRLineEdit.setObjectName("cmpRLineEdit")
        self.gridLayout_6.addWidget(self.cmpRLineEdit, 2, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 2, 4, 1, 1)
        self.captureCmpRadius = QtWidgets.QPushButton(self.cmpTab)
        self.captureCmpRadius.setObjectName("captureCmpRadius")
        self.gridLayout_6.addWidget(self.captureCmpRadius, 2, 5, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_6)
        spacerItem9 = QtWidgets.QSpacerItem(20, 272, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem9)
        self.tabWidget.addTab(self.cmpTab, "")
        self.cmpBackgroundTab = QtWidgets.QWidget()
        self.cmpBackgroundTab.setObjectName("cmpBackgroundTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.cmpBackgroundTab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_23 = QtWidgets.QLabel(self.cmpBackgroundTab)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_2.addWidget(self.label_23)
        self.cmpAnulusRadioButton = QtWidgets.QRadioButton(self.cmpBackgroundTab)
        self.cmpAnulusRadioButton.setChecked(True)
        self.cmpAnulusRadioButton.setObjectName("cmpAnulusRadioButton")
        self.horizontalLayout_2.addWidget(self.cmpAnulusRadioButton)
        self.cmpRegionRadioButton = QtWidgets.QRadioButton(self.cmpBackgroundTab)
        self.cmpRegionRadioButton.setObjectName("cmpRegionRadioButton")
        self.horizontalLayout_2.addWidget(self.cmpRegionRadioButton)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.allignCmpVerticalCenter = QtWidgets.QToolButton(self.cmpBackgroundTab)
        self.allignCmpVerticalCenter.setIcon(icon1)
        self.allignCmpVerticalCenter.setCheckable(True)
        self.allignCmpVerticalCenter.setObjectName("allignCmpVerticalCenter")
        self.horizontalLayout_2.addWidget(self.allignCmpVerticalCenter)
        self.lockBackgroundSize2 = QtWidgets.QToolButton(self.cmpBackgroundTab)
        self.lockBackgroundSize2.setIcon(icon)
        self.lockBackgroundSize2.setCheckable(True)
        self.lockBackgroundSize2.setObjectName("lockBackgroundSize2")
        self.horizontalLayout_2.addWidget(self.lockBackgroundSize2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.cmpBackgroundTab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.captureCmpAnulusBackground = QtWidgets.QPushButton(self.groupBox_3)
        self.captureCmpAnulusBackground.setObjectName("captureCmpAnulusBackground")
        self.horizontalLayout_8.addWidget(self.captureCmpAnulusBackground)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 0, 0, 1, 1)
        self.cmpR1LineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.cmpR1LineEdit.setObjectName("cmpR1LineEdit")
        self.gridLayout_4.addWidget(self.cmpR1LineEdit, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 1, 0, 1, 1)
        self.cmpR2LineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.cmpR2LineEdit.setObjectName("cmpR2LineEdit")
        self.gridLayout_4.addWidget(self.cmpR2LineEdit, 1, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_4)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.cmpBackgroundTab)
        self.groupBox_4.setEnabled(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.captureCmpRegionBackground = QtWidgets.QPushButton(self.groupBox_4)
        self.captureCmpRegionBackground.setObjectName("captureCmpRegionBackground")
        self.horizontalLayout_7.addWidget(self.captureCmpRegionBackground)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_25 = QtWidgets.QLabel(self.groupBox_4)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 0, 0, 1, 1)
        self.cmpX1LineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.cmpX1LineEdit.setObjectName("cmpX1LineEdit")
        self.gridLayout_3.addWidget(self.cmpX1LineEdit, 0, 1, 1, 1)
        self.cmpX2LineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.cmpX2LineEdit.setObjectName("cmpX2LineEdit")
        self.gridLayout_3.addWidget(self.cmpX2LineEdit, 0, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 1, 0, 1, 1)
        self.cmpY1LineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.cmpY1LineEdit.setObjectName("cmpY1LineEdit")
        self.gridLayout_3.addWidget(self.cmpY1LineEdit, 1, 1, 1, 1)
        self.cmpY2LineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.cmpY2LineEdit.setObjectName("cmpY2LineEdit")
        self.gridLayout_3.addWidget(self.cmpY2LineEdit, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.cmpBackgroundTab, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem13)
        self.cancelButton = QtWidgets.QPushButton(PhotometryConfigWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_9.addWidget(self.cancelButton)
        self.saveButton = QtWidgets.QPushButton(PhotometryConfigWidget)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_9.addWidget(self.saveButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)

        self.retranslateUi(PhotometryConfigWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.tgtAnulusRadioButton, QtCore.SIGNAL("toggled(bool)"), self.groupBox_2.setEnabled)
        QtCore.QObject.connect(self.tgtAnulusRadioButton, QtCore.SIGNAL("toggled(bool)"), self.groupBox.setDisabled)
        QtCore.QObject.connect(self.previousButton, QtCore.SIGNAL("clicked()"), self.imageSpinBox.stepDown)
        QtCore.QObject.connect(self.nextButton, QtCore.SIGNAL("clicked()"), self.imageSpinBox.stepUp)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL("clicked()"), PhotometryConfigWidget.close)
        QtCore.QObject.connect(self.cmpAnulusRadioButton, QtCore.SIGNAL("toggled(bool)"), self.groupBox_3.setEnabled)
        QtCore.QObject.connect(self.cmpAnulusRadioButton, QtCore.SIGNAL("toggled(bool)"), self.groupBox_4.setDisabled)
        QtCore.QObject.connect(self.lockObjectSizes, QtCore.SIGNAL("toggled(bool)"), self.lockObjectSizes2.setChecked)
        QtCore.QObject.connect(self.lockObjectSizes2, QtCore.SIGNAL("toggled(bool)"), self.lockObjectSizes.setChecked)
        QtCore.QObject.connect(self.lockBackgroundSize, QtCore.SIGNAL("toggled(bool)"), self.lockBackgroundSize2.setChecked)
        QtCore.QObject.connect(self.lockBackgroundSize2, QtCore.SIGNAL("toggled(bool)"), self.lockBackgroundSize.setChecked)
        QtCore.QMetaObject.connectSlotsByName(PhotometryConfigWidget)
        PhotometryConfigWidget.setTabOrder(self.captureTgt, self.captureTgtRadius)
        PhotometryConfigWidget.setTabOrder(self.captureTgtRadius, self.captureTgtAnulusBackground)
        PhotometryConfigWidget.setTabOrder(self.captureTgtAnulusBackground, self.captureCmp)
        PhotometryConfigWidget.setTabOrder(self.captureCmp, self.captureCmpRadius)
        PhotometryConfigWidget.setTabOrder(self.captureCmpRadius, self.captureCmpAnulusBackground)
        PhotometryConfigWidget.setTabOrder(self.captureCmpAnulusBackground, self.tgtXLineEdit)
        PhotometryConfigWidget.setTabOrder(self.tgtXLineEdit, self.tgtYLineEdit)
        PhotometryConfigWidget.setTabOrder(self.tgtYLineEdit, self.tgtRLineEdit)
        PhotometryConfigWidget.setTabOrder(self.tgtRLineEdit, self.tgtR1LineEdit)
        PhotometryConfigWidget.setTabOrder(self.tgtR1LineEdit, self.tgtR2LineEdit)
        PhotometryConfigWidget.setTabOrder(self.tgtR2LineEdit, self.cmpXLineEdit)
        PhotometryConfigWidget.setTabOrder(self.cmpXLineEdit, self.cmpYLineEdit)
        PhotometryConfigWidget.setTabOrder(self.cmpYLineEdit, self.cmpRLineEdit)
        PhotometryConfigWidget.setTabOrder(self.cmpRLineEdit, self.cmpR1LineEdit)
        PhotometryConfigWidget.setTabOrder(self.cmpR1LineEdit, self.cmpR2LineEdit)
        PhotometryConfigWidget.setTabOrder(self.cmpR2LineEdit, self.tgtRecenterCheckBox)
        PhotometryConfigWidget.setTabOrder(self.tgtRecenterCheckBox, self.cmpRecenterCheckBox)
        PhotometryConfigWidget.setTabOrder(self.cmpRecenterCheckBox, self.tgtAnulusRadioButton)
        PhotometryConfigWidget.setTabOrder(self.tgtAnulusRadioButton, self.tgtRegionRadioButton)
        PhotometryConfigWidget.setTabOrder(self.tgtRegionRadioButton, self.captureTgtRegionBackground)
        PhotometryConfigWidget.setTabOrder(self.captureTgtRegionBackground, self.tgtX1LineEdit)
        PhotometryConfigWidget.setTabOrder(self.tgtX1LineEdit, self.tgtX2LineEdit)
        PhotometryConfigWidget.setTabOrder(self.tgtX2LineEdit, self.tgtY1LineEdit)
        PhotometryConfigWidget.setTabOrder(self.tgtY1LineEdit, self.tgtY2LineEdit)
        PhotometryConfigWidget.setTabOrder(self.tgtY2LineEdit, self.cmpAnulusRadioButton)
        PhotometryConfigWidget.setTabOrder(self.cmpAnulusRadioButton, self.cmpRegionRadioButton)
        PhotometryConfigWidget.setTabOrder(self.cmpRegionRadioButton, self.captureCmpRegionBackground)
        PhotometryConfigWidget.setTabOrder(self.captureCmpRegionBackground, self.cmpX1LineEdit)
        PhotometryConfigWidget.setTabOrder(self.cmpX1LineEdit, self.cmpX2LineEdit)
        PhotometryConfigWidget.setTabOrder(self.cmpX2LineEdit, self.cmpY1LineEdit)
        PhotometryConfigWidget.setTabOrder(self.cmpY1LineEdit, self.cmpY2LineEdit)
        PhotometryConfigWidget.setTabOrder(self.cmpY2LineEdit, self.tabWidget)

    def retranslateUi(self, PhotometryConfigWidget):
        PhotometryConfigWidget.setWindowTitle(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Form", None, QtWidgets.QApplication.UnicodeUTF8))
        self.previousButton.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Previous", None, QtWidgets.QApplication.UnicodeUTF8))
        self.nextButton.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Next", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tgtRecenterCheckBox.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Recenter on object", None, QtWidgets.QApplication.UnicodeUTF8))
        self.lockObjectSizes.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "...", None, QtWidgets.QApplication.UnicodeUTF8))
        self.label_12.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Position:", None, QtWidgets.QApplication.UnicodeUTF8))
        self.label.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "x", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tgtXLineEdit.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "0", None, QtWidgets.QApplication.UnicodeUTF8))
        self.label_2.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "y", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tgtYLineEdit.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "0", None, QtWidgets.QApplication.UnicodeUTF8))
        self.captureTgt.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Capture", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tgtEndPosLabel.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "End Position:", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tgtEndXLabel.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "x", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tgtXEndLineEdit.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "0", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tgtEndYLabel.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "y", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tgtYEndLineEdit.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "0", None, QtWidgets.QApplication.UnicodeUTF8))
        self.captureTgtEnd.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Capture", None, QtWidgets.QApplication.UnicodeUTF8))
        self.label_13.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Size:", None, QtWidgets.QApplication.UnicodeUTF8))
        self.label_3.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "r", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tgtRLineEdit.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "5", None, QtWidgets.QApplication.UnicodeUTF8))
        self.captureTgtRadius.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Capture", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tgtTab), QtWidgets.QApplication.translate("PhotometryConfigWidget", "Target", None, QtWidgets.QApplication.UnicodeUTF8))
        self.label_7.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Type:", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tgtAnulusRadioButton.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Annulus", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tgtRegionRadioButton.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Region", None, QtWidgets.QApplication.UnicodeUTF8))
        self.allignTgtVerticalCenter.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "...", None, QtWidgets.QApplication.UnicodeUTF8))
        self.lockBackgroundSize.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "...", None, QtWidgets.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Annulus parameters", None, QtWidgets.QApplication.UnicodeUTF8))
        self.captureTgtAnulusBackground.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Capture", None, QtWidgets.QApplication.UnicodeUTF8))
        self.label_10.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Radius Start", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tgtR1LineEdit.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "0", None, QtWidgets.QApplication.UnicodeUTF8))
        self.label_11.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Radius End", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tgtR2LineEdit.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "0", None, QtWidgets.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Region parameters", None, QtWidgets.QApplication.UnicodeUTF8))
        self.captureTgtRegionBackground.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Capture", None, QtWidgets.QApplication.UnicodeUTF8))
        self.label_8.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "X Range", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tgtX1LineEdit.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "0", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tgtX2LineEdit.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "0", None, QtWidgets.QApplication.UnicodeUTF8))
        self.label_9.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Y Range", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tgtY1LineEdit.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "0", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tgtY2LineEdit.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "0", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tgtBackgroundTab), QtWidgets.QApplication.translate("PhotometryConfigWidget", "Target Background", None, QtWidgets.QApplication.UnicodeUTF8))
        self.cmpRecenterCheckBox.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Recenter on object", None, QtWidgets.QApplication.UnicodeUTF8))
        self.lockObjectSizes2.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "...", None, QtWidgets.QApplication.UnicodeUTF8))
        self.label_18.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Position:", None, QtWidgets.QApplication.UnicodeUTF8))
        self.label_16.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "x", None, QtWidgets.QApplication.UnicodeUTF8))
        self.cmpXLineEdit.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "0", None, QtWidgets.QApplication.UnicodeUTF8))
        self.label_15.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "y", None, QtWidgets.QApplication.UnicodeUTF8))
        self.cmpYLineEdit.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "0", None, QtWidgets.QApplication.UnicodeUTF8))
        self.captureCmp.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Capture", None, QtWidgets.QApplication.UnicodeUTF8))
        self.cmpEndPosLabel.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "End Position:", None, QtWidgets.QApplication.UnicodeUTF8))
        self.cmpEndXLabel.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "x", None, QtWidgets.QApplication.UnicodeUTF8))
        self.cmpXEndLineEdit.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "0", None, QtWidgets.QApplication.UnicodeUTF8))
        self.cmpEndYLabel.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "y", None, QtWidgets.QApplication.UnicodeUTF8))
        self.cmpYEndLineEdit.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "0", None, QtWidgets.QApplication.UnicodeUTF8))
        self.captureCmpEnd.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Capture", None, QtWidgets.QApplication.UnicodeUTF8))
        self.label_19.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Size:", None, QtWidgets.QApplication.UnicodeUTF8))
        self.label_20.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "r", None, QtWidgets.QApplication.UnicodeUTF8))
        self.cmpRLineEdit.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "5", None, QtWidgets.QApplication.UnicodeUTF8))
        self.captureCmpRadius.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Capture", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cmpTab), QtWidgets.QApplication.translate("PhotometryConfigWidget", "Comparison", None, QtWidgets.QApplication.UnicodeUTF8))
        self.label_23.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Type:", None, QtWidgets.QApplication.UnicodeUTF8))
        self.cmpAnulusRadioButton.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Annulus", None, QtWidgets.QApplication.UnicodeUTF8))
        self.cmpRegionRadioButton.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Region", None, QtWidgets.QApplication.UnicodeUTF8))
        self.allignCmpVerticalCenter.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "...", None, QtWidgets.QApplication.UnicodeUTF8))
        self.lockBackgroundSize2.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "...", None, QtWidgets.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Annulus parameters", None, QtWidgets.QApplication.UnicodeUTF8))
        self.captureCmpAnulusBackground.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Capture", None, QtWidgets.QApplication.UnicodeUTF8))
        self.label_21.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Radius Start", None, QtWidgets.QApplication.UnicodeUTF8))
        self.cmpR1LineEdit.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "0", None, QtWidgets.QApplication.UnicodeUTF8))
        self.label_22.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Radius End", None, QtWidgets.QApplication.UnicodeUTF8))
        self.cmpR2LineEdit.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "0", None, QtWidgets.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Region parameters", None, QtWidgets.QApplication.UnicodeUTF8))
        self.captureCmpRegionBackground.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Capture", None, QtWidgets.QApplication.UnicodeUTF8))
        self.label_25.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "X Range", None, QtWidgets.QApplication.UnicodeUTF8))
        self.cmpX1LineEdit.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "0", None, QtWidgets.QApplication.UnicodeUTF8))
        self.cmpX2LineEdit.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "0", None, QtWidgets.QApplication.UnicodeUTF8))
        self.label_24.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Y Range", None, QtWidgets.QApplication.UnicodeUTF8))
        self.cmpY1LineEdit.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "0", None, QtWidgets.QApplication.UnicodeUTF8))
        self.cmpY2LineEdit.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "0", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cmpBackgroundTab), QtWidgets.QApplication.translate("PhotometryConfigWidget", "Comparison Background", None, QtWidgets.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "Cancel", None, QtWidgets.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtWidgets.QApplication.translate("PhotometryConfigWidget", "OK", None, QtWidgets.QApplication.UnicodeUTF8))

import icons_rc
